<?php
// $config['enable_query_strings'] = TRUE;
$config['page_query_string']    = TRUE;
$config['per_page']             = 9;
// $config['prefix']               = '';
// $config['suffix']               = '';
$config['full_tag_open']        = '<ul class="pagination justify-content-center">';
$config['full_tag_close']       ='</ul>';
$config['num_tag_open']         = '<li class="page-item"><span class="page-link">';
$config['num_tag_close']        = '</span></li>';
$config['cur_tag_open']         = '<li class="page-item active"><a class="page-link" href="#">';
$config['cur_tag_close']        = '</a></li>';
$config['prev_tag_open']        = '<li class="page-item"><span class="page-link">';
$config['prev_tag_close']       = '</span></li>';
$config['next_tag_open']        = '<li class="page-item"><span class="page-link">';
$config['next_tag_close']       = '</span></li>';
// $config['prev_link']            = '<i class="icon-backward"></i>';
// $config['next_link']            = '<i class="icon-forward"></i>';
$config['last_tag_open']        = '<li class="page-item"><span class="page-link">';
$config['last_tag_close']       = '</span></li>';
$config['first_tag_open']       = '<li class="page-item"><span class="page-link">';
$config['first_tag_close']      = '</span></li>';
